language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO="django>=1.8,<1.10"
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls coverage django-discover-runner
script:
  - coverage run --rcfile=.coveragerc setup.py test
after_success:
  - coveralls